'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OkoshiMAX.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Add_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property AlwaysVisible_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlwaysVisible_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Bookmark_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bookmark_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Cancel_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cancel_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property CaptureFrame_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CaptureFrame_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property DestinationAssistant_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DestinationAssistant_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property DownloadDocument_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DownloadDocument_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Featured_playlist_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Featured-playlist-01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property FolderClosed_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FolderClosed_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property GlyphRight_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GlyphRight_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property ifn0304() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ifn0304", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Monitor_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Monitor_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property OkoshiMAX1_5_0() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("OkoshiMAX1_5_0", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property OpenFolder_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFolder_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Pause_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property PinnedItem_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PinnedItem_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property PlayVideo_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayVideo_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Run_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Run_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property SettingsOutline_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SettingsOutline_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Stop_grey_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop_grey_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Volume_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Volume_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  {0}x{1} のような形式のクリップボード画像タイトル文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ClipboardImageTitle() As String
            Get
                Return ResourceManager.GetString("ClipboardImageTitle", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  クリップボードに画像がない場合のメッセージを検索します。
        '''</summary>
        Friend ReadOnly Property NoClipboardImage() As String
            Get
                Return ResourceManager.GetString("NoClipboardImage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  エラーダイアログのタイトルを検索します。
        '''</summary>
        Friend ReadOnly Property [Error]() As String
            Get
                Return ResourceManager.GetString("Error", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  保存する画像がない場合のメッセージを検索します。
        '''</summary>
        Friend ReadOnly Property NoImageToSave() As String
            Get
                Return ResourceManager.GetString("NoImageToSave", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  確認ダイアログのタイトルを検索します。
        '''</summary>
        Friend ReadOnly Property Confirm() As String
            Get
                Return ResourceManager.GetString("Confirm", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  画像保存ダイアログのフィルタ文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ImageSaveFilter() As String
            Get
                Return ResourceManager.GetString("ImageSaveFilter", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  画像保存ダイアログのタイトルを検索します。
        '''</summary>
        Friend ReadOnly Property SaveImage() As String
            Get
                Return ResourceManager.GetString("SaveImage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  画像保存完了メッセージを検索します。
        '''</summary>
        Friend ReadOnly Property ImageSaved() As String
            Get
                Return ResourceManager.GetString("ImageSaved", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  画像読み込み失敗メッセージを検索します。
        '''</summary>
        Friend ReadOnly Property ImageLoadFailed() As String
            Get
                Return ResourceManager.GetString("ImageLoadFailed", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  保存失敗メッセージを検索します。
        '''</summary>
        Friend ReadOnly Property SaveFailed() As String
            Get
                Return ResourceManager.GetString("SaveFailed", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  ショートカットキー入力要求メッセージを検索します。
        '''</summary>
        Friend ReadOnly Property EnterShortcutKey() As String
            Get
                Return ResourceManager.GetString("EnterShortcutKey", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  設定完了メッセージを検索します。
        '''</summary>
        Friend ReadOnly Property SettingsComplete() As String
            Get
                Return ResourceManager.GetString("SettingsComplete", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  キー設定削除メッセージを検索します。
        '''</summary>
        Friend ReadOnly Property KeySettingsDeleted() As String
            Get
                Return ResourceManager.GetString("KeySettingsDeleted", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  エクスポート完了メッセージを検索します。
        '''</summary>
        Friend ReadOnly Property ExportComplete() As String
            Get
                Return ResourceManager.GetString("ExportComplete", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  エクスポート失敗メッセージを検索します。
        '''</summary>
        Friend ReadOnly Property ExportFailed() As String
            Get
                Return ResourceManager.GetString("ExportFailed", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  桁数超過エラーメッセージを検索します。
        '''</summary>
        Friend ReadOnly Property DigitsExceeded() As String
            Get
                Return ResourceManager.GetString("DigitsExceeded", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  カウンタ超過エラーメッセージを検索します。
        '''</summary>
        Friend ReadOnly Property CounterExceedsDuration() As String
            Get
                Return ResourceManager.GetString("CounterExceedsDuration", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Word ファイル読み込み失敗メッセージを検索します。
        '''</summary>
        Friend ReadOnly Property WordFileLoadFailed() As String
            Get
                Return ResourceManager.GetString("WordFileLoadFailed", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  非対応ファイル形式エラーメッセージを検索します。
        '''</summary>
        Friend ReadOnly Property FileFormatNotSupported() As String
            Get
                Return ResourceManager.GetString("FileFormatNotSupported", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  画面キャプチャ未実装メッセージを検索します。
        '''</summary>
        Friend ReadOnly Property ScreenCaptureNotImplemented() As String
            Get
                Return ResourceManager.GetString("ScreenCaptureNotImplemented", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  メディア未読み込みエラーメッセージを検索します。
        '''</summary>
        Friend ReadOnly Property NoMediaLoaded() As String
            Get
                Return ResourceManager.GetString("NoMediaLoaded", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  キャプチャ保存完了メッセージを検索します。
        '''</summary>
        Friend ReadOnly Property ScreenCaptureSaved() As String
            Get
                Return ResourceManager.GetString("ScreenCaptureSaved", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  キャプチャ失敗エラーメッセージを検索します。
        '''</summary>
        Friend ReadOnly Property ScreenCaptureFailed() As String
            Get
                Return ResourceManager.GetString("ScreenCaptureFailed", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  無効な数字入力エラーメッセージを検索します。
        '''</summary>
        Friend ReadOnly Property InvalidDigits() As String
            Get
                Return ResourceManager.GetString("InvalidDigits", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  時間フォーマット文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TimeFormat() As String
            Get
                Return ResourceManager.GetString("TimeFormat", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  速度フォーマット文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SpeedFormat() As String
            Get
                Return ResourceManager.GetString("SpeedFormat", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  音量フォーマット文字列を検索します。
        '''</summary>
        Friend ReadOnly Property VolumeFormat() As String
            Get
                Return ResourceManager.GetString("VolumeFormat", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  時間区切り文字列を検索します。
        '''</summary>
        Friend ReadOnly Property TimeSeparator() As String
            Get
                Return ResourceManager.GetString("TimeSeparator", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
