'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自動保存機能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastOpenedFile() As String
            Get
                Return CType(Me("LastOpenedFile"),String)
            End Get
            Set
                Me("LastOpenedFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property AutoBack() As Integer
            Get
                Return CType(Me("AutoBack"),Integer)
            End Get
            Set
                Me("AutoBack") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LastIchi() As Double
            Get
                Return CType(Me("LastIchi"),Double)
            End Get
            Set
                Me("LastIchi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Atama() As String
            Get
                Return CType(Me("Atama"),String)
            End Get
            Set
                Me("Atama") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Oshiri() As String
            Get
                Return CType(Me("Oshiri"),String)
            End Get
            Set
                Me("Oshiri") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property MyLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("MyLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("MyLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MyClientSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("MyClientSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("MyClientSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK1() As Integer
            Get
                Return CType(Me("SK1"),Integer)
            End Get
            Set
                Me("SK1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK2() As Integer
            Get
                Return CType(Me("SK2"),Integer)
            End Get
            Set
                Me("SK2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK3() As Integer
            Get
                Return CType(Me("SK3"),Integer)
            End Get
            Set
                Me("SK3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK4() As Integer
            Get
                Return CType(Me("SK4"),Integer)
            End Get
            Set
                Me("SK4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK5() As Integer
            Get
                Return CType(Me("SK5"),Integer)
            End Get
            Set
                Me("SK5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK6() As Integer
            Get
                Return CType(Me("SK6"),Integer)
            End Get
            Set
                Me("SK6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK7() As Integer
            Get
                Return CType(Me("SK7"),Integer)
            End Get
            Set
                Me("SK7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK8() As Integer
            Get
                Return CType(Me("SK8"),Integer)
            End Get
            Set
                Me("SK8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK9() As Integer
            Get
                Return CType(Me("SK9"),Integer)
            End Get
            Set
                Me("SK9") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK10() As Integer
            Get
                Return CType(Me("SK10"),Integer)
            End Get
            Set
                Me("SK10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK11() As Integer
            Get
                Return CType(Me("SK11"),Integer)
            End Get
            Set
                Me("SK11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK12() As Integer
            Get
                Return CType(Me("SK12"),Integer)
            End Get
            Set
                Me("SK12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK13() As Integer
            Get
                Return CType(Me("SK13"),Integer)
            End Get
            Set
                Me("SK13") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK14() As Integer
            Get
                Return CType(Me("SK14"),Integer)
            End Get
            Set
                Me("SK14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK15() As Integer
            Get
                Return CType(Me("SK15"),Integer)
            End Get
            Set
                Me("SK15") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK16() As Integer
            Get
                Return CType(Me("SK16"),Integer)
            End Get
            Set
                Me("SK16") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK17() As Integer
            Get
                Return CType(Me("SK17"),Integer)
            End Get
            Set
                Me("SK17") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK18() As Integer
            Get
                Return CType(Me("SK18"),Integer)
            End Get
            Set
                Me("SK18") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK19() As Integer
            Get
                Return CType(Me("SK19"),Integer)
            End Get
            Set
                Me("SK19") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SK20() As Integer
            Get
                Return CType(Me("SK20"),Integer)
            End Get
            Set
                Me("SK20") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKA() As Short
            Get
                Return CType(Me("SKA"),Short)
            End Get
            Set
                Me("SKA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKB() As Short
            Get
                Return CType(Me("SKB"),Short)
            End Get
            Set
                Me("SKB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKC() As Short
            Get
                Return CType(Me("SKC"),Short)
            End Get
            Set
                Me("SKC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKD() As Short
            Get
                Return CType(Me("SKD"),Short)
            End Get
            Set
                Me("SKD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKE() As Short
            Get
                Return CType(Me("SKE"),Short)
            End Get
            Set
                Me("SKE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKAA() As Short
            Get
                Return CType(Me("SKAA"),Short)
            End Get
            Set
                Me("SKAA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKBA() As Short
            Get
                Return CType(Me("SKBA"),Short)
            End Get
            Set
                Me("SKBA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKCA() As Short
            Get
                Return CType(Me("SKCA"),Short)
            End Get
            Set
                Me("SKCA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKDA() As Short
            Get
                Return CType(Me("SKDA"),Short)
            End Get
            Set
                Me("SKDA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKEA() As Short
            Get
                Return CType(Me("SKEA"),Short)
            End Get
            Set
                Me("SKEA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Onryou() As Integer
            Get
                Return CType(Me("Onryou"),Integer)
            End Get
            Set
                Me("Onryou") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MM1() As Integer
            Get
                Return CType(Me("MM1"),Integer)
            End Get
            Set
                Me("MM1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MM2() As Integer
            Get
                Return CType(Me("MM2"),Integer)
            End Get
            Set
                Me("MM2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MM3() As Integer
            Get
                Return CType(Me("MM3"),Integer)
            End Get
            Set
                Me("MM3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HO1() As Integer
            Get
                Return CType(Me("HO1"),Integer)
            End Get
            Set
                Me("HO1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HO2() As Integer
            Get
                Return CType(Me("HO2"),Integer)
            End Get
            Set
                Me("HO2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HO3() As Integer
            Get
                Return CType(Me("HO3"),Integer)
            End Get
            Set
                Me("HO3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKM1() As Short
            Get
                Return CType(Me("SKM1"),Short)
            End Get
            Set
                Me("SKM1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKM1A() As Short
            Get
                Return CType(Me("SKM1A"),Short)
            End Get
            Set
                Me("SKM1A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKM2() As Short
            Get
                Return CType(Me("SKM2"),Short)
            End Get
            Set
                Me("SKM2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKM2A() As Short
            Get
                Return CType(Me("SKM2A"),Short)
            End Get
            Set
                Me("SKM2A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKM3() As Short
            Get
                Return CType(Me("SKM3"),Short)
            End Get
            Set
                Me("SKM3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKM3A() As Short
            Get
                Return CType(Me("SKM3A"),Short)
            End Get
            Set
                Me("SKM3A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKH1() As Short
            Get
                Return CType(Me("SKH1"),Short)
            End Get
            Set
                Me("SKH1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKH1A() As Short
            Get
                Return CType(Me("SKH1A"),Short)
            End Get
            Set
                Me("SKH1A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKH2() As Short
            Get
                Return CType(Me("SKH2"),Short)
            End Get
            Set
                Me("SKH2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKH2A() As Short
            Get
                Return CType(Me("SKH2A"),Short)
            End Get
            Set
                Me("SKH2A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKH3() As Short
            Get
                Return CType(Me("SKH3"),Short)
            End Get
            Set
                Me("SKH3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKH3A() As Short
            Get
                Return CType(Me("SKH3A"),Short)
            End Get
            Set
                Me("SKH3A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Setting() As Short
            Get
                Return CType(Me("Setting"),Short)
            End Get
            Set
                Me("Setting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKF() As Short
            Get
                Return CType(Me("SKF"),Short)
            End Get
            Set
                Me("SKF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKFA() As Short
            Get
                Return CType(Me("SKFA"),Short)
            End Get
            Set
                Me("SKFA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Atama2() As String
            Get
                Return CType(Me("Atama2"),String)
            End Get
            Set
                Me("Atama2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Oshiri2() As String
            Get
                Return CType(Me("Oshiri2"),String)
            End Get
            Set
                Me("Oshiri2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TimeCode() As Short
            Get
                Return CType(Me("TimeCode"),Short)
            End Get
            Set
                Me("TimeCode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Atama3() As String
            Get
                Return CType(Me("Atama3"),String)
            End Get
            Set
                Me("Atama3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Oshiri3() As String
            Get
                Return CType(Me("Oshiri3"),String)
            End Get
            Set
                Me("Oshiri3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKG() As Short
            Get
                Return CType(Me("SKG"),Short)
            End Get
            Set
                Me("SKG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKH() As Short
            Get
                Return CType(Me("SKH"),Short)
            End Get
            Set
                Me("SKH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKI() As Short
            Get
                Return CType(Me("SKI"),Short)
            End Get
            Set
                Me("SKI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKJ() As Short
            Get
                Return CType(Me("SKJ"),Short)
            End Get
            Set
                Me("SKJ") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKK() As Short
            Get
                Return CType(Me("SKK"),Short)
            End Get
            Set
                Me("SKK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKL() As Short
            Get
                Return CType(Me("SKL"),Short)
            End Get
            Set
                Me("SKL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKM() As Short
            Get
                Return CType(Me("SKM"),Short)
            End Get
            Set
                Me("SKM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKN() As Short
            Get
                Return CType(Me("SKN"),Short)
            End Get
            Set
                Me("SKN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKO() As Short
            Get
                Return CType(Me("SKO"),Short)
            End Get
            Set
                Me("SKO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKP() As Short
            Get
                Return CType(Me("SKP"),Short)
            End Get
            Set
                Me("SKP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKGA() As Short
            Get
                Return CType(Me("SKGA"),Short)
            End Get
            Set
                Me("SKGA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKHA() As Short
            Get
                Return CType(Me("SKHA"),Short)
            End Get
            Set
                Me("SKHA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKIA() As Short
            Get
                Return CType(Me("SKIA"),Short)
            End Get
            Set
                Me("SKIA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKJA() As Short
            Get
                Return CType(Me("SKJA"),Short)
            End Get
            Set
                Me("SKJA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKKA() As Short
            Get
                Return CType(Me("SKKA"),Short)
            End Get
            Set
                Me("SKKA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKLA() As Short
            Get
                Return CType(Me("SKLA"),Short)
            End Get
            Set
                Me("SKLA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKMA() As Short
            Get
                Return CType(Me("SKMA"),Short)
            End Get
            Set
                Me("SKMA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKNA() As Short
            Get
                Return CType(Me("SKNA"),Short)
            End Get
            Set
                Me("SKNA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKOA() As Short
            Get
                Return CType(Me("SKOA"),Short)
            End Get
            Set
                Me("SKOA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKPA() As Short
            Get
                Return CType(Me("SKPA"),Short)
            End Get
            Set
                Me("SKPA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKQA() As Short
            Get
                Return CType(Me("SKQA"),Short)
            End Get
            Set
                Me("SKQA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKRA() As Short
            Get
                Return CType(Me("SKRA"),Short)
            End Get
            Set
                Me("SKRA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKSA() As Short
            Get
                Return CType(Me("SKSA"),Short)
            End Get
            Set
                Me("SKSA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKTA() As Short
            Get
                Return CType(Me("SKTA"),Short)
            End Get
            Set
                Me("SKTA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKUA() As Short
            Get
                Return CType(Me("SKUA"),Short)
            End Get
            Set
                Me("SKUA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKVA() As Short
            Get
                Return CType(Me("SKVA"),Short)
            End Get
            Set
                Me("SKVA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKWA() As Short
            Get
                Return CType(Me("SKWA"),Short)
            End Get
            Set
                Me("SKWA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKXA() As Short
            Get
                Return CType(Me("SKXA"),Short)
            End Get
            Set
                Me("SKXA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKYA() As Short
            Get
                Return CType(Me("SKYA"),Short)
            End Get
            Set
                Me("SKYA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKZA() As Short
            Get
                Return CType(Me("SKZA"),Short)
            End Get
            Set
                Me("SKZA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKQ() As Short
            Get
                Return CType(Me("SKQ"),Short)
            End Get
            Set
                Me("SKQ") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKR() As Short
            Get
                Return CType(Me("SKR"),Short)
            End Get
            Set
                Me("SKR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKS() As Short
            Get
                Return CType(Me("SKS"),Short)
            End Get
            Set
                Me("SKS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKT() As Short
            Get
                Return CType(Me("SKT"),Short)
            End Get
            Set
                Me("SKT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKU() As Short
            Get
                Return CType(Me("SKU"),Short)
            End Get
            Set
                Me("SKU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKV() As Short
            Get
                Return CType(Me("SKV"),Short)
            End Get
            Set
                Me("SKV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKW() As Short
            Get
                Return CType(Me("SKW"),Short)
            End Get
            Set
                Me("SKW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKX() As Short
            Get
                Return CType(Me("SKX"),Short)
            End Get
            Set
                Me("SKX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKY() As Short
            Get
                Return CType(Me("SKY"),Short)
            End Get
            Set
                Me("SKY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKZ() As Short
            Get
                Return CType(Me("SKZ"),Short)
            End Get
            Set
                Me("SKZ") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property p11_width() As Integer
            Get
                Return CType(Me("p11_width"),Integer)
            End Get
            Set
                Me("p11_width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property p11_height() As Integer
            Get
                Return CType(Me("p11_height"),Integer)
            End Get
            Set
                Me("p11_height") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property p12_width() As Integer
            Get
                Return CType(Me("p12_width"),Integer)
            End Get
            Set
                Me("p12_width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property p12_height() As Integer
            Get
                Return CType(Me("p12_height"),Integer)
            End Get
            Set
                Me("p12_height") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property p21_width() As Integer
            Get
                Return CType(Me("p21_width"),Integer)
            End Get
            Set
                Me("p21_width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property p21_height() As Integer
            Get
                Return CType(Me("p21_height"),Integer)
            End Get
            Set
                Me("p21_height") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property p22_width() As Integer
            Get
                Return CType(Me("p22_width"),Integer)
            End Get
            Set
                Me("p22_width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property p22_height() As Integer
            Get
                Return CType(Me("p22_height"),Integer)
            End Get
            Set
                Me("p22_height") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property gamen() As Boolean
            Get
                Return CType(Me("gamen"),Boolean)
            End Get
            Set
                Me("gamen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property shiori() As Boolean
            Get
                Return CType(Me("shiori"),Boolean)
            End Get
            Set
                Me("shiori") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property SC1() As Short
            Get
                Return CType(Me("SC1"),Short)
            End Get
            Set
                Me("SC1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property SC2() As Short
            Get
                Return CType(Me("SC2"),Short)
            End Get
            Set
                Me("SC2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("110")>  _
        Public Property SC3() As Short
            Get
                Return CType(Me("SC3"),Short)
            End Get
            Set
                Me("SC3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("120")>  _
        Public Property SC4() As Short
            Get
                Return CType(Me("SC4"),Short)
            End Get
            Set
                Me("SC4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("130")>  _
        Public Property SC5() As Short
            Get
                Return CType(Me("SC5"),Short)
            End Get
            Set
                Me("SC5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("140")>  _
        Public Property SC6() As Short
            Get
                Return CType(Me("SC6"),Short)
            End Get
            Set
                Me("SC6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("150")>  _
        Public Property SC7() As Short
            Get
                Return CType(Me("SC7"),Short)
            End Get
            Set
                Me("SC7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SC1A() As Short
            Get
                Return CType(Me("SC1A"),Short)
            End Get
            Set
                Me("SC1A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SC2A() As Short
            Get
                Return CType(Me("SC2A"),Short)
            End Get
            Set
                Me("SC2A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SC3A() As Short
            Get
                Return CType(Me("SC3A"),Short)
            End Get
            Set
                Me("SC3A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SC4A() As Short
            Get
                Return CType(Me("SC4A"),Short)
            End Get
            Set
                Me("SC4A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SC5A() As Short
            Get
                Return CType(Me("SC5A"),Short)
            End Get
            Set
                Me("SC5A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SC6A() As Short
            Get
                Return CType(Me("SC6A"),Short)
            End Get
            Set
                Me("SC6A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SC7A() As Short
            Get
                Return CType(Me("SC7A"),Short)
            End Get
            Set
                Me("SC7A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKSC1() As Short
            Get
                Return CType(Me("SKSC1"),Short)
            End Get
            Set
                Me("SKSC1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKSC2() As Short
            Get
                Return CType(Me("SKSC2"),Short)
            End Get
            Set
                Me("SKSC2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKSC3() As Short
            Get
                Return CType(Me("SKSC3"),Short)
            End Get
            Set
                Me("SKSC3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKSC4() As Short
            Get
                Return CType(Me("SKSC4"),Short)
            End Get
            Set
                Me("SKSC4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKSC5() As Short
            Get
                Return CType(Me("SKSC5"),Short)
            End Get
            Set
                Me("SKSC5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKSC6() As Short
            Get
                Return CType(Me("SKSC6"),Short)
            End Get
            Set
                Me("SKSC6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SKSC7() As Short
            Get
                Return CType(Me("SKSC7"),Short)
            End Get
            Set
                Me("SKSC7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Fuka() As String
            Get
                Return CType(Me("Fuka"),String)
            End Get
            Set
                Me("Fuka") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Fumei() As String
            Get
                Return CType(Me("Fumei"),String)
            End Get
            Set
                Me("Fumei") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Sonota() As String
            Get
                Return CType(Me("Sonota"),String)
            End Get
            Set
                Me("Sonota") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property shokai() As Integer
            Get
                Return CType(Me("shokai"),Integer)
            End Get
            Set
                Me("shokai") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.OkoshiMAX.My.MySettings
            Get
                Return Global.OkoshiMAX.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
